### ISSUE TITLE
Approvers should not need approval

### ISSUE THREAD

**Issue by ggggg** [utmgdsc/hacklab-booking#244]
Bookings by approvers should automatically be approved, they should not need to select an approver either:
![image](https://github.com/user-attachments/assets/821fdaf2-cc79-43a0-a16b-9a2eeda2a1a6)

**Comment by FrederickPu** [comment]
can I take this one?

**Comment by ggggg** [comment]
Hi Fredrick, this issue is already assigned and on the develop brunch. But feel free to choose any other issue to work on!

**Comment by FrederickPu** [comment]
how do you see issue assignments?
